version: "3"
services:
  database:
    image: postgres:14.5
    container_name: db_container_tms_v2
    hostname: db_container_tms
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    command: -p 5433

    volumes:
      - pg_data_tms:/var/lib/postgresql/data

  backend:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  pg_data_tms: