version: "3"
services:
  database:
    image: postgres:14.5
    container_name: db_container_tms
    hostname: db_container_tms
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

  backend:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
