version: "3"
services:
  database:
    image: postgres:14.5
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"

#  backend:
##    depends_on:
##      - database
#    build: .
#    ports:
#      - "8080:8080"


