spring:
  application:
    name: team_management_system

  datasource:
    url: jdbc:postgresql://db_container_tms:5433/team_management
    username: postgres
    password: 1

  flyway:
    baselineOnMigrate: true

