name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.0
      with:
        arguments: copyAppJar
        gradle-version: 7.6

    - name: Print directory
      run: |
        tree -d .
        echo ${{ secrets.DOCKER_USERNAME }}
        echo ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6.1
      with:
        image: tms/springboot-image-new
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
