name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.0
      with:
        arguments: copyAppJar
        gradle-version: 7.6

    - name: Print directory
      run: |
        tree -d .
        ls build/output-docker
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: backend-artifacts
        path: .

  build-image:
  
    runs-on: ubuntu-latest
    
    needs:
      - build-backend
    
    steps:
        
    - uses: actions/download-artifact@v3
      with:
        name: backend-artifacts
        path: .
        
    - name: Display structure of downloaded files
      run: ls -R

    - name: Print directory
      run: |
        tree -d .
        ls build/output-docker

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: garrri/team_management_system:latest
